export const SERVER_ERROR = 'SERVER_ERROR'
export const LOGIN_ALREADY_REGISTRED = 'LOGIN_ALREADY_REGISTRED'
export const EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE'
export const PASSWORD_DOES_NOT_MATCH = 'PASSWORD_DOES_NOT_MATCH'

export const ERROR_MESSAGES = {
    ERROR_EMAIL_EXISTS: 'Email already in use!'
}